### ISSUE TITLE
Not working if added to late game

### ISSUE THREAD

**Issue by nelwa** [CaptainKlutz/GenericSkyscrapersSource#1]
Hi,

I've got a game currently in year 2170.  I got a little bored, and added your NewGFX since it looks real nice.  But buildings don't change to your graphics.  I think it might be because I only added it after the buildings' introduction dates.  Am I correct?

Is there anything I can do about it?

**Comment by nelwa** [comment]
Hi, just to follow up, I've tested your NewGRF with a new game as well, and the buildings doesn't show.  Is there some sort of required plugin?

**Comment by nelwa** [comment]
Apologies, I now realize these buildings don't build by themselves.  They are manually placed eye candy only.  Unfortunate.

**Comment by CaptainKlutz** [comment]
> 
> 
> Apologies, I now realize these buildings don't build by themselves. They are manually placed eye candy only. Unfortunate.

Hi, the original GRF (Californian City Objects by Luxtram, I believe) does what you're looking for here and adds these buildings to the town construction list.
